### ISSUE TITLE
Map svn usernames to github name/email address

### ISSUE THREAD

**Issue by duncan3dc** [tn5250j/migration#1]
The list of svn contributors is below, please comment if you'd like your name/email changed

```
golthar             =   Barry van Someren <golthar@users.sourceforge.net>
joep_beckeringh     =   Joep Beckeringh <joep_beckeringh@users.sourceforge.net>
jorjun              =   Peter Moore <jorjun@users.sourceforge.net>
kennedyz            =   Steve Kennedy <kennedyz@users.sourceforge.net>
mbrilli             =   Maurizio Brilli <mbrilli@users.sourceforge.net>
nicolaken           =   Nicola Ken Barozzi <nicolaken@users.sourceforge.net>
ozgunm              =   Mehmet Ozgun <ozgunm@users.sourceforge.net>
pbielen             =   Patrick Bielen <pbielen@users.sourceforge.net>
rupshall            =   Robert Upshall <rupshall@users.sourceforge.net>

chrisgt             =   Christian Geisert <christian.geisert@isu-gmbh.de>
master_jaf          =   Martin W. Kirst <maki@bitkings.de>
phelgren            =   Pete Helgren <pete@valadd.com>
kjp1                =   Kenneth J. Pouncey <kjp1@users.sourceforge.net>
(no author)         =   Kenneth J. Pouncey <kjp1@users.sourceforge.net>
root                =   Kenneth J. Pouncey <kjp1@users.sourceforge.net>
```

**Comment by nitram509** [comment]
master_jaf is mapped to [nitram509](https://github.com/nitram509) on Github email maki@bitkings.de

**Comment by phelgren** [comment]
phelgren (Pete Helgren) is phelgren on Github

**Comment by kjpou1** [comment]
kjp1 = kjpou1(Kenneth Pouncey) on Github [kjpou1](https://github.com/kjpou1)
(no author) = kjpou1(Kenneth Pouncey) on Github [kjpou1](https://github.com/kjpou1)
root = kjpou1(Kenneth Pouncey) on Github [kjpou1](https://github.com/kjpou1)

**Comment by chrisgt** [comment]
chrisgt is chrisgt on GitHub ;-)

**Comment by duncan3dc** [comment]
Hi everyone, GitHub uses email addresses to map to your usernames, so we don't need to add your GitHub username anywhere. We just need to use an email address that is linked to your GitHub profile. So you only need to comment if you want to use a different email address than the sourceforge one, thanks

**Comment by chrisgt** [comment]
Ok, chrisgt -> christian.geisert@isu-gmbh.de

**Comment by phelgren** [comment]
Ok...phelgren is pete@valadd.com

**Comment by cycloon** [comment]
If you would like to add me:
sf.net: cycloon -> github.com: cycloon -> email: cycloon@is-root.org

**Comment by duncan3dc** [comment]
Sorry but there are no svn commits by author `cycloon`

**Comment by cycloon** [comment]
Thats ok, as I did not have any. Martin just asked me if I wanted to join and I thought I should ad me here…

**Comment by nitram509** [comment]
@duncan3dc sorry for that confusion. Because I know Christian quite a long time I asked him to join.
He's a long time Tn5250j user, expert and developer.

I appreciate to see this community growing again :-)

**Comment by zippy1981** [comment]
If you count small patches zippy1981 Justin Dearing <zippy1981 at f++mail>

**Comment by duncan3dc** [comment]
All the commits have been mapped to the email addresses provided now:
https://github.com/tn5250j/tn5250j/graphs/contributors

**Comment by cycloon** [comment]
Looks great!

**Comment by bvansomeren** [comment]
Hi, I'm 
golthar             =   Barry van Someren <golthar@users.sourceforge.net> and got an email about this a while ago. (It went to an inbox I didn't check often enough ,sorry)

Personally I don't mind the change at all, unfortunately the work was done as part of my employment way back and I'm unsure where to go to get the proper permissions as I haven't worked there for more than 10 years.

If there is not a lot of code involved it might make sense to scrap / rewrite them.
