### ISSUE TITLE
Migrate the website to gh-pages

### ISSUE THREAD

**Issue by duncan3dc** [tn5250j/migration#2]
Look for a reasonable theme and produce it using jekyll

**Comment by duncan3dc** [comment]
Work in progress:
https://github.com/tn5250j/tn5250j.github.io
http://tn5250j.github.io/

**Comment by cycloon** [comment]
Are there any concerns or must-haves from the original authors or are we free to design a new site? If interested, I could donate and host the domain tn5250j.org (currently not registered)

**Comment by duncan3dc** [comment]
Ping @kjpou1 @nitram509

**Comment by nitram509** [comment]
From my point of view we're totally free.
I appreciate to see  a new site. A lot of things are outdated.

E.g. all documentation about applets, we can get rid off. 
The security issues with applets I consider higher than the general technical benefit.
If one wants to have a web-ready version, WebSockets are the the answer ;-)

**Comment by duncan3dc** [comment]
I've stripped out a lot of the old content, as it referred to very old versions of tn5250j, or old versions of java. But all of the essential stuff is there now

**Comment by nitram509** [comment]
:+1:
