### ISSUE TITLE
Find a place to store the binary release files

### ISSUE THREAD

**Issue by duncan3dc** [tn5250j/migration#3]
Maybe just a separate branch that we can just commit the files to

**Comment by nitram509** [comment]
Other alternatives:
- https://bintray.com/

Example: https://bintray.com/nitram509/tn5250j

**Comment by nitram509** [comment]
Using Github releases seems to be perfect:
https://github.com/blog/1547-release-your-software

**Comment by duncan3dc** [comment]
Yes I wasn't aware you could attach files to a release, that'll do nicely

**Comment by duncan3dc** [comment]
I've created a release for the latest versions and attached the binaries:
https://github.com/tn5250j/tn5250j/releases/tag/0.7.6
