### ISSUE TITLE
Map the SVN branches

### ISSUE THREAD

**Issue by duncan3dc** [tn5250j/migration#4]
Do we need to bring over the branches? Are they still relevant?

**Comment by duncan3dc** [comment]
@nitram509 I was planning on making the `0.6.x` branch master in github, the other branches don't look active, is there anything we need from them?

**Comment by nitram509** [comment]
I would like to preserve 'new-gui-jse1.6' branch, because it contains interesting new GUI design.
The rest we don't need to care about.

**Comment by nitram509** [comment]
@duncan3dc 

the MASTER should definetly point to TRUNK.
Because a couple of month ago I clarified this.

History:
long time the trunk was not actively released , but releases came from the another branch (I forgot the name)

**Comment by duncan3dc** [comment]
Ahh yes I see that post now, I misunderstood the current structure. So use `trunk/tn5250j`as `master` and keep the `new-gui-jse1.6` branch but `1.6.x` is unmaintained now and can be left behind with the rest?

**Comment by duncan3dc** [comment]
How does the [test](/tn5250j/test) repository look now, is that what you were expecting?

**Comment by nitram509** [comment]
Looks ok so far.
- branches and trunk looks as i would expect
- the names aren't mapped yet (I expect you know about)
- is there a chance to also migrate the tags a.k.a. releases?

**Comment by duncan3dc** [comment]
Which names aren't mapped?

I will look into migrating the tags/releases

**Comment by nitram509** [comment]
@duncan3dc 
I've looked into https://github.com/tn5250j/test and my name isn't mapped correctly.
In the 'commits' view I expect to see my avatar, but it's not.

So to me mapping doesn't work yet.

**Comment by duncan3dc** [comment]
Sorry, I didn't see you'd changed your email address in #1, I'll get the test repo updated.
But you can see from the [contributors view](https://github.com/tn5250j/test/graphs/contributors) that the mapping is working

**Comment by nitram509** [comment]
This contributor view seems to be a nice "test util" ;-)

When you change my email, please also consider to look at Pete Helgren and Kenneth J. Pouncey.
I've spotted them on page 11 (July-Sept.2005): https://github.com/tn5250j/test/commits/master?page=11
But I miss them on the contributors view.

**Comment by duncan3dc** [comment]
Everyone that provides an email address in #1 will be mapped, so Pete will be fine, but Kenneth hasn't given an email address linked to his GitHub profile

**Comment by duncan3dc** [comment]
As the branches are ok I'll close this issue now, mapping is being handled in #1, and I'll create a new issue to migrate tags/releases
