### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by duncan3dc** [tn5250j/migration#5]
Provide common links and instructions, a brief explanation of the history of the project including the move from sourceforge

**Comment by nitram509** [comment]
@duncan3dc 

very elegant and transparent idea to handle the migration this way :+1:

**Comment by nitram509** [comment]
@duncan3dc 

Ping: it seems to me the migration broke down?
Any news?

**Comment by duncan3dc** [comment]
Hey, it's still on my radar, just been super busy lately. I'll get it up and running again before the end of the month :+1:

**Comment by nitram509** [comment]
Cool. thanks.

**Comment by duncan3dc** [comment]
This has been added now: https://github.com/tn5250j/tn5250j/blob/382515eb0fed944affa6b93aadf8c78b35bbc06d/README.md
