### ISSUE TITLE
Migrate open issues to Github

### ISSUE THREAD

**Issue by nitram509** [tn5250j/migration#6]
- kick everything older than 1 year
  - provide links to Github to help users when the bug/patch/feature request is still valid.
- close all tickets on source forge to make visible no one will have a look on.

**Comment by duncan3dc** [comment]
I'm not sure there's a neat way to migrate this stuff, it would just be a case of manually opening new tickets, what do you think about closing each sourceforge ticket with the following text?

---

Thanks for contributing to tn5250j. We recently made the decision to move future development/discussion to the GitHub platform. (https://github.com/tn5250j/tn5250j)
Please could we ask that you re-open your issue there and we would be happy to continue the discussion.
Thank you

**Comment by nitram509** [comment]
+1 for closing old tickets
Since the majority is outdated anyway ;)

**Comment by duncan3dc** [comment]
Cool, can you do that now?
Are you ready to make the switch to GitHub? I think everything is in order.
